/** Static quiz subjects and the wider answer pool used by Snake Spotter. */

export type SnakeSpecies = {
  id: string;
  name: string;
  scientificName: string;
  image: string;
  averageLength: string;
  geography: string;
  facts: [string, string];
};

export const FEATURED_SNAKES: SnakeSpecies[] = [
  {
    id: "ball-python",
    name: "Ball python",
    scientificName: "Python regius",
    image: "photos/ball-python.webp",
    averageLength: "1.2 m",
    geography: "West and Central Africa",
    facts: [
      "This gentle constrictor curls into a tight ball when it feels threatened.",
      "It is non-venomous and uses heat-sensing pits around its mouth to find warm-blooded prey.",
    ],
  },
  {
    id: "boa-constrictor",
    name: "Boa constrictor",
    scientificName: "Boa constrictor",
    image: "photos/boa-constrictor.webp",
    averageLength: "2–3 m",
    geography: "Central and South America",
    facts: [
      "A boa squeezes prey with its powerful coils instead of using venom.",
      "Unlike many snakes, it gives birth to live young rather than laying eggs.",
    ],
  },
  {
    id: "burmese-python",
    name: "Burmese python",
    scientificName: "Python bivittatus",
    image: "photos/burmese-python.webp",
    averageLength: "3.7 m",
    geography: "South and South-east Asia",
    facts: [
      "This heavyweight constrictor can stay underwater for around half an hour.",
      "It is non-venomous, but its huge size means people should always give wild ones plenty of space.",
    ],
  },
  {
    id: "reticulated-python",
    name: "Reticulated python",
    scientificName: "Malayopython reticulatus",
    image: "photos/reticulated-python.webp",
    averageLength: "4.8 m",
    geography: "South and South-east Asia",
    facts: [
      "The net-like pattern gives this python its name: reticulated means arranged like a net.",
      "It is the world’s longest snake species and is a powerful, non-venomous constrictor.",
    ],
  },
  {
    id: "king-cobra",
    name: "King cobra",
    scientificName: "Ophiophagus hannah",
    image: "photos/king-cobra.webp",
    averageLength: "3–3.6 m",
    geography: "South and South-east Asia",
    facts: [
      "The world’s longest venomous snake mainly eats other snakes—even cobras.",
      "It is the only snake known to build a nest for its eggs, which the female guards fiercely.",
    ],
  },
  {
    id: "indian-cobra",
    name: "Indian cobra",
    scientificName: "Naja naja",
    image: "photos/indian-cobra.webp",
    averageLength: "1.5 m",
    geography: "The Indian subcontinent",
    facts: [
      "When alarmed, it spreads its neck ribs into a famous broad hood.",
      "Its venom can be deadly, but it usually tries to escape and should be watched only from a safe distance.",
    ],
  },
  {
    id: "black-mamba",
    name: "Black mamba",
    scientificName: "Dendroaspis polylepis",
    image: "photos/black-mamba.webp",
    averageLength: "2.5 m",
    geography: "Sub-Saharan Africa",
    facts: [
      "Its body is usually grey or olive—the dramatic name comes from the inky-black inside of its mouth.",
      "It is fast, highly venomous and normally uses its speed to flee from danger.",
    ],
  },
  {
    id: "green-anaconda",
    name: "Green anaconda",
    scientificName: "Eunectes murinus",
    image: "photos/green-anaconda.webp",
    averageLength: "4.5 m",
    geography: "Tropical South America",
    facts: [
      "This non-venomous constrictor is the heaviest snake species on Earth.",
      "Its eyes and nostrils sit high on its head, so it can see and breathe while almost completely underwater.",
    ],
  },
  {
    id: "corn-snake",
    name: "Corn snake",
    scientificName: "Pantherophis guttatus",
    image: "photos/corn-snake.webp",
    averageLength: "1.2 m",
    geography: "South-eastern United States",
    facts: [
      "This harmless constrictor helps farmers by eating mice and rats around grain stores.",
      "The chequered pattern on its belly can look a little like colourful kernels of maize.",
    ],
  },
  {
    id: "milk-snake",
    name: "Milk snake",
    scientificName: "Lampropeltis triangulum",
    image: "photos/milk-snake.webp",
    averageLength: "0.9 m",
    geography: "North and Central America",
    facts: [
      "The old tale that this snake drinks cows’ milk is a myth—it was really hunting rodents in barns.",
      "It is a harmless constrictor whose bright bands can resemble those of a venomous coral snake.",
    ],
  },
  {
    id: "western-diamondback",
    name: "Western diamondback rattlesnake",
    scientificName: "Crotalus atrox",
    image: "photos/western-diamondback.webp",
    averageLength: "1.2 m",
    geography: "South-western United States and Mexico",
    facts: [
      "Its tail rattle is made of hollow keratin segments that buzz when shaken.",
      "It has dangerous venom and heat-sensing facial pits, so a rattling snake should always be given lots of room.",
    ],
  },
  {
    id: "eastern-coral",
    name: "Eastern coral snake",
    scientificName: "Micrurus fulvius",
    image: "photos/eastern-coral.webp",
    averageLength: "0.6 m",
    geography: "South-eastern United States",
    facts: [
      "Its bright red, yellow and black rings warn predators that it carries powerful venom.",
      "It is secretive and spends much of its time hidden under leaves or underground.",
    ],
  },
  {
    id: "gaboon-viper",
    name: "Gaboon viper",
    scientificName: "Bitis gabonica",
    image: "photos/gaboon-viper.webp",
    averageLength: "1.2 m",
    geography: "Central and West African rainforests",
    facts: [
      "Its leaf-like pattern is superb camouflage on the rainforest floor.",
      "It has the longest fangs of any snake and a large venom supply, but it is usually calm and relies on hiding.",
    ],
  },
  {
    id: "puff-adder",
    name: "Puff adder",
    scientificName: "Bitis arietans",
    image: "photos/puff-adder.webp",
    averageLength: "1 m",
    geography: "Africa and the Arabian Peninsula",
    facts: [
      "When threatened, it inflates its body and makes a loud, warning hiss—hence the name ‘puff’ adder.",
      "It is venomous and often stays perfectly still, trusting its zigzag camouflage.",
    ],
  },
  {
    id: "inland-taipan",
    name: "Inland taipan",
    scientificName: "Oxyuranus microlepidotus",
    image: "photos/inland-taipan.webp",
    averageLength: "2 m",
    geography: "Inland eastern Australia",
    facts: [
      "It has the most toxic venom of any land snake, yet bites are extremely rare because it is shy and remote.",
      "Its colour darkens in winter, helping it soak up warmth from the sun.",
    ],
  },
  {
    id: "boomslang",
    name: "Boomslang",
    scientificName: "Dispholidus typus",
    image: "photos/boomslang.webp",
    averageLength: "1.5 m",
    geography: "Sub-Saharan Africa",
    facts: [
      "Boomslang means ‘tree snake’ in Afrikaans, and this agile climber hunts among branches.",
      "It has potent venom and unusually large eyes, but it is timid and generally avoids people.",
    ],
  },
  {
    id: "emerald-tree-boa",
    name: "Emerald tree boa",
    scientificName: "Corallus caninus",
    image: "photos/emerald-tree-boa.webp",
    averageLength: "1.8 m",
    geography: "Amazon Basin, South America",
    facts: [
      "It rests in a neat saddle shape over a branch, with its head balanced in the centre.",
      "Young snakes are orange or red and turn brilliant green as they grow; they are non-venomous constrictors.",
    ],
  },
  {
    id: "california-kingsnake",
    name: "California kingsnake",
    scientificName: "Lampropeltis californiae",
    image: "photos/california-kingsnake.webp",
    averageLength: "1 m",
    geography: "Western United States and northern Mexico",
    facts: [
      "This non-venomous constrictor is called a kingsnake because it can hunt other snakes.",
      "It has some resistance to rattlesnake venom and comes in striped or banded patterns.",
    ],
  },
  {
    id: "common-garter",
    name: "Common garter snake",
    scientificName: "Thamnophis sirtalis",
    image: "photos/common-garter.webp",
    averageLength: "0.7 m",
    geography: "North America",
    facts: [
      "This adaptable snake can live in gardens, woods and wetlands, often close to water.",
      "It gives birth to live young and is not dangerous to humans, though its saliva is mildly venomous to tiny prey.",
    ],
  },
  {
    id: "eastern-hognose",
    name: "Eastern hognose snake",
    scientificName: "Heterodon platirhinos",
    image: "photos/eastern-hognose.webp",
    averageLength: "0.7 m",
    geography: "Eastern North America",
    facts: [
      "Its upturned snout works like a little shovel for digging in sandy soil.",
      "If its dramatic hissing and neck-flattening act fails, this harmless-to-humans snake may roll over and play dead.",
    ],
  },
  {
    id: "eastern-diamondback",
    name: "Eastern diamondback rattlesnake",
    scientificName: "Crotalus adamanteus",
    image: "photos/eastern-diamondback.webp",
    averageLength: "0.8–1.8 m",
    geography: "South-eastern United States",
    facts: [
      "This is North America’s longest and heaviest venomous snake, with bold diamond markings down its back.",
      "Its heat-sensing pits help it ambush warm-blooded prey, and its rattle gives a warning when it feels threatened.",
    ],
  },
  {
    id: "copperhead",
    name: "Copperhead",
    scientificName: "Agkistrodon contortrix",
    image: "photos/copperhead.webp",
    averageLength: "0.76 m",
    geography: "Eastern North America",
    facts: [
      "Its copper-coloured head and hourglass-shaped bands vanish surprisingly well among fallen leaves.",
      "Young copperheads wiggle a bright yellow tail tip like a caterpillar to lure small prey; the species is venomous.",
    ],
  },
  {
    id: "cottonmouth",
    name: "Cottonmouth",
    scientificName: "Agkistrodon piscivorus",
    image: "photos/cottonmouth.webp",
    averageLength: "1.2 m",
    geography: "South-eastern United States",
    facts: [
      "This semi-aquatic pit viper is an excellent swimmer and often floats with its head and body high in the water.",
      "Its name comes from the bright white mouth it displays as a warning; its venom can cause serious injury.",
    ],
  },
  {
    id: "green-tree-python",
    name: "Green tree python",
    scientificName: "Morelia viridis",
    image: "photos/green-tree-python.webp",
    averageLength: "1.5 m",
    geography: "New Guinea, eastern Indonesia and north-eastern Australia",
    facts: [
      "This non-venomous python loops over branches and uses its gripping tail like an extra hand.",
      "Hatchlings can be yellow or red-brown, changing to their famous leaf-green colour as they grow.",
    ],
  },
  {
    id: "eyelash-viper",
    name: "Eyelash viper",
    scientificName: "Bothriechis schlegelii",
    image: "photos/eyelash-viper.webp",
    averageLength: "0.6 m",
    geography: "Tropical Central and north-western South America",
    facts: [
      "Pointed scales above its eyes look like tiny eyelashes and may help break up its outline among leaves.",
      "This small tree-dwelling pit viper comes in dazzling colours and is venomous, so it should never be approached.",
    ],
  },
  {
    id: "eastern-brown",
    name: "Eastern brown snake",
    scientificName: "Pseudonaja textilis",
    image: "photos/eastern-brown.webp",
    averageLength: "1.5 m",
    geography: "Eastern Australia and southern New Guinea",
    facts: [
      "Its colour varies from pale tan to almost black, and young snakes may wear dark bands that fade with age.",
      "It has extremely potent venom but also controls farm pests by hunting introduced rats and mice.",
    ],
  },
  {
    id: "tiger-snake",
    name: "Tiger snake",
    scientificName: "Notechis scutatus",
    image: "photos/tiger-snake.webp",
    averageLength: "1.2 m",
    geography: "Southern Australia and nearby islands",
    facts: [
      "Many have tiger-like bands, but this remarkably variable snake can also be plain, olive or almost black.",
      "It is a strong swimmer often found near wetlands, and its powerful venom makes giving it space essential.",
    ],
  },
  {
    id: "yellow-anaconda",
    name: "Yellow anaconda",
    scientificName: "Eunectes notaeus",
    image: "photos/yellow-anaconda.webp",
    averageLength: "3 m",
    geography: "Southern South America",
    facts: [
      "Smaller than its green anaconda cousin, it wears dark saddles across a yellow-green body.",
      "This non-venomous constrictor spends lots of time in swamps and slow water, where it hunts from ambush.",
    ],
  },
  {
    id: "rainbow-boa",
    name: "Rainbow boa",
    scientificName: "Epicrates cenchria",
    image: "photos/rainbow-boa.webp",
    averageLength: "1.5–2 m",
    geography: "Tropical South America",
    facts: [
      "Microscopic ridges on its scales split light into colours, creating a brilliant rainbow shimmer.",
      "It is a non-venomous constrictor that usually explores the rainforest floor and low branches at night.",
    ],
  },
  {
    id: "grass-snake",
    name: "Grass snake",
    scientificName: "Natrix natrix",
    image: "photos/grass-snake.webp",
    averageLength: "0.9–1.5 m",
    geography: "Continental Europe and western Asia",
    facts: [
      "Look for the pale collar behind its head; this harmless snake is a keen swimmer that often hunts frogs.",
      "When frightened it may hiss, release a terrible smell or dramatically play dead instead of biting.",
    ],
  },
];

export const ALL_SNAKE_NAMES = [
  "African bush viper",
  "African egg-eating snake",
  "Amazon tree boa",
  "Angolan python",
  "Arizona coral snake",
  "Asian vine snake",
  "Ball python",
  "Banded krait",
  "Black mamba",
  "Black rat snake",
  "Black-necked spitting cobra",
  "Blue krait",
  "Boa constrictor",
  "Boomslang",
  "Brahminy blind snake",
  "Brown tree snake",
  "Bullsnake",
  "Burmese python",
  "California kingsnake",
  "Cape cobra",
  "Carpet python",
  "Central American bushmaster",
  "Coachwhip",
  "Common death adder",
  "Common garter snake",
  "Common lancehead",
  "Copperhead",
  "Corn snake",
  "Cottonmouth",
  "Desert horned viper",
  "Eastern brown snake",
  "Eastern coral snake",
  "Eastern diamondback rattlesnake",
  "Eastern green mamba",
  "Eastern hognose snake",
  "Egyptian cobra",
  "Emerald tree boa",
  "Eyelash viper",
  "False water cobra",
  "Fer-de-lance",
  "Gaboon viper",
  "Gopher snake",
  "Grass snake",
  "Green anaconda",
  "Green tree python",
  "Indian cobra",
  "Indian python",
  "Inland taipan",
  "Jamaican boa",
  "Japanese rat snake",
  "King cobra",
  "King rat snake",
  "Madagascar ground boa",
  "Mangrove snake",
  "Massasauga",
  "Mexican black kingsnake",
  "Milk snake",
  "Mojave rattlesnake",
  "Monocled cobra",
  "Olive sea snake",
  "Paradise flying snake",
  "Pine snake",
  "Prairie rattlesnake",
  "Puff adder",
  "Pygmy python",
  "Rainbow boa",
  "Red-bellied black snake",
  "Red spitting cobra",
  "Reticulated python",
  "Rhinoceros viper",
  "Ring-necked snake",
  "Rosy boa",
  "Rough green snake",
  "Saharan horned viper",
  "Scarlet kingsnake",
  "Sidewinder",
  "Speckled kingsnake",
  "Spotted python",
  "Sunbeam snake",
  "Taiwan beauty snake",
  "Tentacled snake",
  "Texas indigo snake",
  "Tiger snake",
  "Timber rattlesnake",
  "Titanoboa",
  "Twig snake",
  "Urutu",
  "Wagler's pit viper",
  "Water python",
  "Western diamondback rattlesnake",
  "Western green mamba",
  "Western hognose snake",
  "White-lipped python",
  "Yellow anaconda",
  "Yellow-bellied sea snake",
  "Yellow-blotched palm pit viper",
  "Yellow rat snake",
  "Yellow-lipped sea krait",
  "Zebra snake",
  "Zigzag vine snake",
] as const;
